version: '3.8'

services:
  coral-growth-monitor:
    build:
      context: ./coral-growth-monitor-service
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - microservices-network

  scheduling:
    build:
      context: ./scheduling-service
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "8001:8001"
    networks:
      - microservices-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8671/eureka

  resource-allocation:
    build:
      context: ./resource-allocation-service
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "8002:8002"
    networks:
      - microservices-network

  user-recommendation-service:
    build:
      context: ./user-recommendation-service
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "8003:8003"
    networks:
      - microservices-network
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8671/eureka
      - RATINGS_FILE_PATH=/app/ratings_final.txt
      - USER_MAP_FILE_PATH=/app/user_mapping.json
      - ITEM_MAP_FILE_PATH=/app/item_mapping.json
      - KG_FILE_PATH=/app/kg_final.txt
      - POST_MAP_FILE_PATH=/app/post_mapping.json
    volumes:
      - ./user-recommendation-service/ratings_final.txt:/app/ratings_final.txt
      - ./user-recommendation-service/user_mapping.json:/app/user_mapping.json
      - ./user-recommendation-service/item_mapping.json:/app/item_mapping.json
      - ./user-recommendation-service/kg_final.txt:/app/kg_final.txt
      - ./user-recommendation-service/post_mapping.json:/app/post_mapping.json

  naming-server:
    build:
      context: ./naming-server
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "8671:8671"
    networks:
      - microservices-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8671/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "8888:8765"
    networks:
      - microservices-network
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8671/eureka

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    mem_limit: 700m
    ports:
      - "50505:50505"
    networks:
      - microservices-network
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8671/eureka

  flask-server:
    build:
      context: ./flask-service
      dockerfile: Dockerfile
    mem_limit: 4g
    ports:
      - "5000:5000"
    networks:
      - microservices-network
    depends_on:
      - naming-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8671/eureka
      - RATINGS_FILE_PATH=/app/ratings_final.txt
      - KG_FILE_PATH=/app/kg_final.txt
      - WATCH_PATH=/app/user-recommendation-service/
    volumes:
      - ./user-recommendation-service/ratings_final.txt:/app/ratings_final.txt
      - ./user-recommendation-service/kg_final.txt:/app/kg_final.txt
      - ./flask-service/app/models/kgcn_model:/app/models/kgcn_model
      - ./flask-service/app/models/coral-growth-monitor-service/coral_polyp_model3.pt:/app/models/coral-growth-monitor-service/coral_polyp_model3.pt

networks:
  microservices-network:
